# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e5fdce685b3f35745540f70412b73abdd8169b1b7d7514548f83e7983a076fcd9a6efbb2434a74b3437bfb633bc26e2147534da007c450d8ca1faa7584ed8b9

test:
  secret_key_base: 7e1936893d52ee71116807faf84e583b5a65665d3742c76a9f800838e0bff9a8f98388f8bf82a73911f8497ce014b7085b38655396b7c21d4f0b707db0a6cf34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
